### ISSUE TITLE
Adding Jupyter-Notebook for Logistic Regression (Categorical Classification)

### ISSUE THREAD

**Issue by m1-key** [ContriHUB/OneML_ContriHub#1]
Currently, there is no notebook for Logistic Regression, so you can add one written with brute force as well as using the library. Follow the Linear Regression Notebook to get the idea of how to make one.

**Comment by AnuragGupta806** [comment]
I want to work on this issue
There is already a notebook for Logistic regression in tutorials folder. Do I have to redo it again?

**Comment by m1-key** [comment]
You have to add a theoretical notebook for this. Explaining what is Logistic Regression and few formulas ( like sigmoid ).

**Comment by AnuragGupta806** [comment]
Do I need to add this theory in the existing notebook or in a new one?

**Comment by m1-key** [comment]
Add another notebook. And change the code accordingly so that one can see the theory part. 
For help you can follow the Linear Regression section as it ia complete and have theory section. 
If you want to work on the issue, let me know then.
