### ISSUE TITLE
Change target url for django api acesss

### ISSUE THREAD

**Issue by m1-key** [ContriHUB/OneML_ContriHub#11]
Currently, the API request for `imageseg` and `thug life` playground is directed to `server.oneml.xyz` which does not exist anymore. Change that to http://localhost:8000. Find the required files and make the necessary changes.

**Comment by umang537** [comment]
Can I work on this?

**Comment by viraj28** [comment]
Ok you may assign @Umang-19 since she requested first.

**Comment by umang537** [comment]
> Ok you may assign @Umang-19 since he requested first.

She* :)

**Comment by viraj28** [comment]
Oops sorry, didn't see.
