### ISSUE TITLE
Render the "Dataset visualization" plot of K-Means using plotly

### ISSUE THREAD

**Issue by sidhantagar** [ContriHUB/OneML_ContriHub#19]
Rewrite code to render the "Dataset visualization" plot in K-Means using plotly.

Refer to expectedoutput1.html in the expected outputs folder for the desired output.

**Comment by sidhantagar** [comment]
In order to contribute to this issue, refer to the additional contributing guide [here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide)

**Comment by umang537** [comment]
I wanna work on this. Kindly assign.

**Comment by umang537** [comment]
[Done. Kindly Check](https://www.kaggle.com/umangaggarwal/contrihub-k-means)

**Comment by sidhantagar** [comment]
The plots are good. You can go ahead and raise a PR
