### ISSUE TITLE
Render the "Visualizing the Loss plot" of K-Means using plotly

### ISSUE THREAD

**Issue by sidhantagar** [ContriHUB/OneML_ContriHub#20]
Rewrite code to render the "Visualizing the Loss plot" in K-Means using plotly.

Refer to expectedoutput2.html in the expected outputs folder for the desired output.

**Comment by sidhantagar** [comment]
In order to contribute to this issue, refer to the additional contributing guide [here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide)

**Comment by umang537** [comment]
Request sent. Kindly assign. :)

**Comment by umang537** [comment]
[Kindly Check](https://www.kaggle.com/umangaggarwal/contrihub-k-means?scriptVersionId=76688917)

**Comment by sidhantagar** [comment]
The plot is a little off. We have used 10 iterations starting from 1. There was a slight error in the expected outputs file. Also please add a dark blue border to differentiate the points.

**Comment by umang537** [comment]
> The plot is a little off. We have used 10 iterations starting from 1. There was a slight error in the expected outputs file. Also please add a dark blue border to differentiate the points.

[Okay. Added :) ](https://www.kaggle.com/umangaggarwal/contrihub-k-means)

**Comment by sidhantagar** [comment]
Raise a PR for the issue. 👍
