### ISSUE TITLE
Render the "Visualizing the convergence of cluster centers" plot in K-Means using plotly

### ISSUE THREAD

**Issue by sidhantagar** [ContriHUB/OneML_ContriHub#21]
Write code to render the "Visualizing the convergence of cluster centers plot" in K-Means using plotly.

Refer to expectedoutput3.html in the expected outputs folder for the desired output.

**Comment by sidhantagar** [comment]
In order to contribute to this issue, refer to the additional contributing guide [here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide)

**Comment by umang537** [comment]
I wanna work on this

**Comment by umang537** [comment]
[Kindly check](https://www.kaggle.com/umangaggarwal/contrihub-k-means)

**Comment by sidhantagar** [comment]
It's good you can raise a PR for it.
