### ISSUE TITLE
Render the "Visualization of the final cluster centers" in K-Means using plotly

### ISSUE THREAD

**Issue by sidhantagar** [ContriHUB/OneML_ContriHub#22]
Rewrite code to render the "Visualization of the final cluster centers" in K-Means using plotly.

Refer to expectedoutput4.html in the expected outputs folder for the desired output.

**Comment by sidhantagar** [comment]
In order to contribute to this issue, refer to the additional contributing guide [here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide)

**Comment by umang537** [comment]
I want to work on this but the K Means Clustering link is showing error 404. [Here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide)
Kindly check.

**Comment by sidhantagar** [comment]
> I want to work on this but the K Means Clustering link is showing error 404. [Here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide) Kindly check.

The Kaggle notebook was private. Now it should be visible.

**Comment by umang537** [comment]
> > I want to work on this but the K Means Clustering link is showing error 404. [Here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide) Kindly check.
> 
> The Kaggle notebook was private. Now it should be visible.

Yes, it's visible. I've forked the Kaggle notebook but getting "code editor out of sync" popup and not able to make any changes.

**Comment by sidhantagar** [comment]
> > > I want to work on this but the K Means Clustering link is showing error 404. [Here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide) Kindly check.
> > 
> > The Kaggle notebook was private. Now it should be visible.
> 
> Yes, it's visible. I've forked the Kaggle notebook but getting "code editor out of sync" popup and not able to make any changes. 

Reload the page or try forking it again.

**Comment by umang537** [comment]
I need help in solving this issue. I've plotted using 2 methods but didn't get the expected output. 
[Link to the notebook.](https://www.kaggle.com/umangaggarwal/contrihub-k-means?scriptVersionId=76598637) 
Could you please give me some suggestions on how to do this?

**Comment by sidhantagar** [comment]
The first method would be the optimal way to go. The reason you are facing this issue is that even though you have used a trace of go.Scatter(), go.Scatter is actually used to plot both line as well as scatter plots and in the current implementation, it is considering a line plot rather than a scatter plot. Look up the attribute "mode" in go.Scatter()

Although this can also be done using the latter method, using the high-level API (plotly-express) will not provide the desired results easily. 

All the best!

**Comment by umang537** [comment]
> The first method would be the optimal way to go. The reason you are facing this issue is that even though you have used a trace of go.Scatter(), go.Scatter is actually used to plot both line as well as scatter plots and in the current implementation, it is considering a line plot rather than a scatter plot. Look up the attribute "mode" in go.Scatter()
> 
> Although this can also be done using the latter method, using the high-level API (plotly-express) will not provide the desired results easily.
> 
> All the best!

Thank you! It worked! 
[Kindly have a look. ](https://www.kaggle.com/umangaggarwal/contrihub-k-means?scriptVersionId=76603279)

**Comment by sidhantagar** [comment]
The Graph has been plotted correctly. Please correct the following before raising the PR:

1. Use a canvas size of 800x800
2. Correct the title of the graph according to the expected output.
3. Correct the layout of the box that shows upon hovering the points.
4. The graph is showing details when hovering on cluster centers as well which should not be visible.
5. Use an opacity of 0.65 for the class points.

Once the above-mentioned changes have been made, raise a PR for the issue.

**Comment by umang537** [comment]
All the above changes have been made. [Check here. ](https://www.kaggle.com/umangaggarwal/contrihub-k-means?scriptVersionId=76618719). 
To create a PR I need to copy the Kaggle code in the K-means notebook present in the K-Means Clustering folder, right?

**Comment by sidhantagar** [comment]
Right and before opening a PR,
There is a stray $ sign on the hover, please remove that.
