### ISSUE TITLE
Render the "Visualization of the dataset" in SVM using plotly

### ISSUE THREAD

**Issue by sidhantagar** [ContriHUB/OneML_ContriHub#26]
Rewrite code to render the "Visualization of the dataset" in Support vector machine using plotly.

Refer to expectedoutput1.html in the expected outputs folder for the desired output.

In order to contribute to this issue, refer to the additional contributing guide [here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide)

**Comment by AnuragGupta806** [comment]
I want to work on this issue

**Comment by AnuragGupta806** [comment]
[Kaggle Notebook](https://www.kaggle.com/anuraggupta806/contrihub-svm/notebook) for SVM dataset visualization

**Comment by sidhantagar** [comment]
Hi Anurag,
There is a stray "," in the trace details of the hover box. Please remove that.
Once completed, you can open a new PR

**Comment by AnuragGupta806** [comment]
Removed stray "," in this [notebook ](https://www.kaggle.com/anuraggupta806/contrihub-svm/notebook). I will open a new PR after Logistic Reg visualization is merged.
