### ISSUE TITLE
Render the "Visualizing the error(Low Penalty)" in SVM using plotly 

### ISSUE THREAD

**Issue by sidhantagar** [ContriHUB/OneML_ContriHub#27]
Rewrite code to render the "Visualizing the error(Low Penalty)" in SVM using plotly.

Refer to expectedoutput2.html in the expected outputs folder for the desired output.

In order to contribute to this issue, refer to the additional contributing guide [here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide)

**Comment by MOULIK-RAZDAN** [comment]
Please Assign.

**Comment by MOULIK-RAZDAN** [comment]
I am having a doubt

that in matplotlib graph the error values are from 200 to 29

but in expected outputs2.html it is from 146 to 26

so in plotly graph do i need to make it from 146 to 26

**Comment by sidhantagar** [comment]
Hi Moulik, actually the starting value is random since a seed has not been set hence before the definition of the SVM model add the code line 
np.random.seed(42)
now the graph will always start from a value of 147

**Comment by MOULIK-RAZDAN** [comment]
Hello Sir,
Sorry for the late reply
Sir after adding the code line  np.random.seed(42)  it is giving the same
output.

**Comment by sidhantagar** [comment]
Please host your notebook on so that I can review the code changes before merging

**Comment by MOULIK-RAZDAN** [comment]
Sir,actually don't add the current pull request because I had earlier made
changes for Kmeans instead of SVM.

**Comment by sidhantagar** [comment]
Okay open a new PR then

**Comment by MOULIK-RAZDAN** [comment]
Sir , I made a new PR

**Comment by MOULIK-RAZDAN** [comment]
Sir I have made a new PR
sir this is the link
https://github.com/ContriHUB/OneML_ContriHub/pull/53

**Comment by sidhantagar** [comment]
Hi moulik could you ping me on teams? I cannot find the code changes made by you to the notebook
