### ISSUE TITLE
Render the "Visualizing the accuracy" in Logistic Regression using plotly

### ISSUE THREAD

**Issue by sidhantagar** [ContriHUB/OneML_ContriHub#31]
Rewrite code to render the "Visualizing the accuracy" in Logistic Regression using plotly

Refer to expectedoutput3.html in the expected outputs folder for the desired output.

In order to contribute to this issue, refer to the additional contributing guide [here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide)

**Comment by AnuragGupta806** [comment]
i want to work on this issue

**Comment by MOULIK-RAZDAN** [comment]
Sir ,is it assigned or not.

**Comment by sidhantagar** [comment]
No it is not assigned

**Comment by MOULIK-RAZDAN** [comment]
Please assign sir

**Comment by MOULIK-RAZDAN** [comment]
Sir please assign the Issue

**Comment by sidhantagar** [comment]
Hi Moulik, Please host the notebook and share it here so that I view the changes made and review them

**Comment by MOULIK-RAZDAN** [comment]
Hello Sir,
Sorry for the late reply
here is the kaggle link -
https://www.kaggle.com/moulikrazdan/contrihub-logistic-regression
changes made for expectedoutputs3.html
