### ISSUE TITLE
Render the "Visualization of the dataset" in Logistic Regression using plotly

### ISSUE THREAD

**Issue by sidhantagar** [ContriHUB/OneML_ContriHub#32]
Rewrite code to render the "Visualization of the dataset" in Logistic Regression using plotly.

Refer to expectedoutput1.html in the expected outputs folder for the desired output.

In order to contribute to this issue, refer to the additional contributing guide [here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide)

**Comment by umang537** [comment]
Request sent on ContriHub. Kindly assign :)

**Comment by sidhantagar** [comment]
Hi Umang, 

As per the additional contributing guidelines mentioned in the [folder](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide), you are not eligible for solving any more plotly issues under the scatter category. This has been done to prevent people from submitting the same code with minor changes and to give others an opportunity to learn and work on the Plotly framework. I would suggest trying out the animated category if you want some challenge or the line category.

All the best!

**Comment by AnuragGupta806** [comment]
I want to work on this issue

**Comment by sidhantagar** [comment]
Hi Anurag could you please raise just one PR and before raising the PR, If you could host the notebook on Kaggle for me to verify the code, that would be amazing

**Comment by AnuragGupta806** [comment]
[Kaggle Notebook](https://www.kaggle.com/anuraggupta806/contrihub-logistic-regression?scriptVersionId=76821666)

**Comment by sidhantagar** [comment]
Hi Anurag,
There is a stray "," in the trace details of the hover box. Please remove that.
Once completed, you can open a new PR

**Comment by AnuragGupta806** [comment]
Removed the stray "," in the new commit in this [PR](https://github.com/ContriHUB/OneML_ContriHub/pull/44) and also in this [notebook](https://www.kaggle.com/anuraggupta806/contrihub-logistic-regression?scriptVersionId=76823198)
