### ISSUE TITLE
Render the "Visualising the error" in Logistic Regression using plotly

### ISSUE THREAD

**Issue by sidhantagar** [ContriHUB/OneML_ContriHub#33]
Rewrite code to render the "Visualizing the error" in Logistic Regression using plotly.

Refer to expectedoutput2.html in the expected outputs folder for the desired output.

In order to contribute to this issue, refer to the additional contributing guide [here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide)

**Comment by umang537** [comment]
Requested. Kindly assign

**Comment by umang537** [comment]
[Is it ok? ](https://www.kaggle.com/umangaggarwal/contrihub-logistic-regression?scriptVersionId=76691838)

**Comment by sidhantagar** [comment]
The kaggle notebook is set to private and hence not visible

**Comment by umang537** [comment]
> The kaggle notebook is set to private and hence not visible

Oh sorry I didn't see it. Check now

**Comment by sidhantagar** [comment]
The graph is a little off. We have the data for 100 iterations but the graph is only showing it for 99 of them.

**Comment by AnuragGupta806** [comment]
i'd like to work on this

**Comment by AnuragGupta806** [comment]
Please check the visualization in this [notebook](https://www.kaggle.com/anuraggupta806/contrihub-logistic-regression).
