### ISSUE TITLE
Render the "Visualizing the convergence of decision boundary" in Logistic Regression using plotly

### ISSUE THREAD

**Issue by sidhantagar** [ContriHUB/OneML_ContriHub#34]
Rewrite code to render the "Visualizing the convergence of decision boundary" in Logistic Regression using plotly

Refer to expectedoutput4.html in the expected outputs folder for the desired output.

In order to contribute to this issue, refer to the additional contributing guide [here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide)

**Comment by umang537** [comment]
Requested. Kindly assign
