### ISSUE TITLE
Render the "Visualization of the decision boundary" in Logistic Regression using plotly

### ISSUE THREAD

**Issue by sidhantagar** [ContriHUB/OneML_ContriHub#35]
Rewrite code to render the "Visualization of the decision boundary" in Logistic Regression using plotly

Refer to expectedoutput5.html in the expected outputs folder for the desired output.

In order to contribute to this issue, refer to the additional contributing guide [here](https://github.com/ContriHUB/OneML_ContriHub/tree/Main/src/utils/tutorial#contributing-guide)

**Comment by MOULIK-RAZDAN** [comment]
please assign sir

**Comment by MOULIK-RAZDAN** [comment]
Sir, I think you have also merged my new commit with the previous commit ,
That is why new PR cannot be generated.

**Comment by MOULIK-RAZDAN** [comment]
Sir this is kaggle link-
https://www.kaggle.com/moulikrazdan/contrihub-logistic-regression-33a91a

**Comment by MOULIK-RAZDAN** [comment]
and Sir could you please tell me how to make PR in this situation
