### ISSUE TITLE
Remove expectedoutput4.html from "expected outputs" of K-Means Clustering folder

### ISSUE THREAD

**Issue by sidhantagar** [ContriHUB/OneML_ContriHub#46]
Folder path: OneML_ContriHub/src/utils/tutorial/K-Means Clustering/expected outputs/

**Comment by kunal2812** [comment]
The file is already removed.

**Comment by sidhantagar** [comment]
As I can see Moulik has mistakenly removed the file. I have changed the issue so that you can make a PR

**Comment by sidhantagar** [comment]
@kunal2812 Please add the line fixes <issue_ number> as a comment on this thread
