### ISSUE TITLE
Add jupyter notebook for Object Classification

### ISSUE THREAD

**Issue by m1-key** [ContriHUB/OneML_ContriHub#8]
Create a jupyter notebook for object classification similar to Linear Regression.

**Comment by kunal2812** [comment]
For the code part, do I need to train a CNN in the notebook or use some pre-trained model for classification?

**Comment by m1-key** [comment]
Try to make your own model, CNN from scratch kind of thing.

**Comment by kunal2812** [comment]
Alright.
